using System;
using System.Reflection;
using System.Resources;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("DayZero Launcher")]
[assembly: AssemblyCompanyAttribute("Zombies.nu")]
[assembly: AssemblyProductAttribute("DayZero Launcher")]
[assembly: AssemblyCopyrightAttribute("Copyright 2013 Zombies.nu")]
[assembly: AssemblyVersionAttribute("1.0.0.6")]
[assembly: AssemblyFileVersionAttribute("1.0.0.6")]

[assembly: NeutralResourcesLanguageAttribute("")]
