using System;
using System.Reflection;
using System.Resources;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


[assembly: AssemblyCompanyAttribute("ZOMBIES.NU")]
[assembly: AssemblyProductAttribute("DayZero")]
[assembly: AssemblyInformationalVersionAttribute("1.2.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright 2013-2014 ZOMBIES.NU")]

[assembly: AssemblyTitleAttribute("DayZero Launcher")]
[assembly: AssemblyVersionAttribute("1.2.3.14")]
[assembly: AssemblyFileVersionAttribute("1.2.3.14")]

[assembly: NeutralResourcesLanguageAttribute("")]
